const PPs = [
	"Mary Baker",
	"Amelia Earhart",
	"Mary Roebling",
	"Sarah Winnemucca",
	"Margaret Brent",
	"Lucy Stone",
	"Mary Edwards",
	"Margaret Chase",
	"Mahalia Jackson",
	"Maya Angelou",
	"Margaret Bourke",
	"Eunice Kennedy",
	"Carrie Chapman",
	"Elizabeth Peratrovich",
	"Alicia Dickerson",
	"Daisy Gatson",
	"Emma Willard",
	"Amelia Boynton",
	"Maria Mitchell",
	"Sojourner Truth",
	"Willa Cather",
	"Coretta Scott",
	"Harriet Tubman",
	"Fabiola Cabeza",
	"Sacagawea",
	"Esther Martinez",
	"Elizabeth Cady",
	"Bessie Coleman",
	"Ma Rainey",
	"Julia Ward",
	"Irene Morgan",
	"Babe Didrikson",
	"Lyda Conley",
	"Annie Dodge",
	"Maud Nathan",
	"Betty Ford",
	"Rosa Parks",
	"Susan La",
	"Gertrude Stein",
	"Wilma Mankiller",
	"Grace Hopper",
	"Jane Addams",
	"Katharine Graham",
	"Florence Chadwick",
	"Zora Neale",
	"Wilma Rudolph",
	"Annie Jump",
	"Mother Frances",
	"Jovita Idár",
	"Maggie L",
	"Henrietta Swan",
	"Jane Cunningham",
	"Victoria Woodhull",
	"Helen Keller",
	"Patsy Takemoto",
	"Chien-Shiung",
	"Dorothea Dix",
	"Margaret Sanger",
	"Alice Paul",
	"Frances Willard",
	"Sally Ride",
	"Juliette Gordon",
	"Queen Lili",
	"Katharine Lee",
	"Harriet Beecher",
	"Felisa Rincon",
	"Hetty Green",
	"Belva Lockwood",
	"Biddy Mason",
	"Ida B",
	"Eleanor Roosevelt",
	"Maria Goeppert",
	"Phillis Wheatley",
	"Mary Harris",
	"Fannie Lou",
	"Rosalyn Yalow",
	"Susan B",
	"Clara Barton",
	"Lady Deborah",
	"Jane Johnston",
	"Alice Childress",
	"Georgia O",
	"Rebecca Crumpler",
	"Anne Bradstreet",
	"Elizabeth Blackwell",
	"Christa McAuliffe",
	"Edmonia Lewis",
	"Nellie Bly",
	"Mary Cassatt",
	"Pauli Murray",
	"Ellen Swallow",
	"Hedy Lamarr",
	"Pearl Kendrick",
	"Abigail Adams",
	"Margaret Fuller",
	"Emma Lazarus",
	"Marian Anderson",
	"Virginia Apgar",
	"Mary Walton"
];

/**
 * it generate the url of a random [boringavatars](https://boringavatars.com) profile picture
 * @param size - size of the squared profile picture, **in pixels**, `DEFAULT=120`
 * @returns {Promise<FunctionJob>} the url of the profile picture
 */
export const GenerateRandomPPUrl = (size = 120): string =>
	`https://source.boringavatars.com/beam/${size}/${encodeURI(
		PPs[Math.round(Math.random() * (PPs.length - 1))]
	)}?colors=3B0503,F67704,F85313,FEDC57,9ECFBC`;
