name: Vitest Tests

on:
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]

defaults:
  run:
    working-directory: tenidditter # run this workflow only on the webapp

jobs:
  testing-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Install NPM Dependencies
        run: pnpm install # Installing dependencies

      - name: Vitest Test
        run: pnpm test
